//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public Articulo()
        {
            this.ArticuloLocal = new HashSet<ArticuloLocal>();
        }
    
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public decimal Unidad_base { get; set; }
    
        public virtual ICollection<ArticuloLocal> ArticuloLocal { get; set; }
    }
}
