//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Local = new HashSet<Local>();
            this.Valoracion = new HashSet<Valoracion>();
        }
    
        public long Rut { get; set; }
        public string Razon_social { get; set; }
        public string Telefono { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<Local> Local { get; set; }
        public virtual ICollection<Valoracion> Valoracion { get; set; }
    }
}
