//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public long IdEstado { get; set; }
        public long TipoEstado { get; set; }
        public string FechaPedido { get; set; }
        public string FechaProceso { get; set; }
        public string FechaEnviado { get; set; }
        public long IdPedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
