//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public Local()
        {
            this.ArticuloLocal = new HashSet<ArticuloLocal>();
            this.EspecificacionLocal = new HashSet<EspecificacionLocal>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public string Nombre { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Direccion { get; set; }
        public decimal Telefono { get; set; }
        public long Rut_empresa { get; set; }
        public string Localidad { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<ArticuloLocal> ArticuloLocal { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<EspecificacionLocal> EspecificacionLocal { get; set; }
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
