//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.Estado1 = new HashSet<Estado>();
        }
    
        public decimal Costo { get; set; }
        public bool Estado { get; set; }
        public long Id_usuario { get; set; }
        public long Id { get; set; }
        public string Nombre_Local { get; set; }
        public string Descripcion { get; set; }
        public string Codigo_html { get; set; }
        public string DireccionPedido { get; set; }
        public string LatitudDireccion { get; set; }
        public string LongitudDireccion { get; set; }
    
        public virtual ICollection<Estado> Estado1 { get; set; }
        public virtual Local Local { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
