//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Pedido = new HashSet<Pedido>();
            this.Ubicacion = new HashSet<Ubicacion>();
            this.Valoracion = new HashSet<Valoracion>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<Pedido> Pedido { get; set; }
        public virtual ICollection<Ubicacion> Ubicacion { get; set; }
        public virtual ICollection<Valoracion> Valoracion { get; set; }
    }
}
